In [58]:
import pandas as pd
import numpy as np

In [59]:
print('Hello')

Hello


In [60]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='fKRhh9XFInLbS1b3WLz6tCMRYuAMWWaGQcKmF_yVBJHC',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us-south.cloud-object-storage.appdomain.cloud')

bucket = 'modeldeployment1-donotdelete-pr-ap6iib0jaqnfjz'
object_key = 'Credit Card Defaulter Prediction.xlsx'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']

dataset = pd.read_excel(body.read())
dataset.head(10)



ID  LIMIT_BAL SEX  EDUCATION_DONE_OR_NOT  MARRIAGE  AGE  PAY_0  PAY_2  \
0   1      20000   F                      1         0   24      2      2   
1   2     120000   F                      1         1   26     -1      2   
2   3      90000   F                      1         0   34      0      0   
3   4      50000   F                      1         1   37      0      0   
4   5      50000   M                      1         1   57     -1      0   
5   6      50000   M                      1         1   37      0      0   
6   7     500000   M                      0         1   29      0      0   
7   8     100000   F                      1         1   23      0     -1   
8   9     140000   F                      1         1   28      0      0   
9  10      20000   M                      0         1   35     -2     -2   

   PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -1     -1  ...          0          0          0         0       689   
1      0      0  ...       3272       3455       3261         0      1000   
2      0      0  ...      14331      14948      15549      1518      1500   
3      0      0  ...      28314      28959      29547      2000      2019   
4     -1      0  ...      20940      19146      19131      2000     36681   
5      0      0  ...      19394      19619      20024      2500      1815   
6      0      0  ...     542653     483003     473944     55000     40000   
7     -1      0  ...        221       -159        567       380       601   
8      2      0  ...      12211      11793       3719      3329         0   
9     -2     -2  ...          0      13007      13912         0         0   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default   
0         0         0         0         0         Y  
1      1000      1000         0      2000         Y  
2      1000      1000      1000      5000         N  
3      1200      1100      1069      1000         N  
4     10000      9000       689       679         N  
5       657      1000      1000       800         N  
6     38000     20239     13750     13770         N  
7         0       581      1687      1542         N  
8       432      1000      1000      1000         N  
9         0     13007      1122         0         N  

[10 rows x 25 columns]

In [61]:
type(dataset)

pandas.core.frame.DataFrame

In [62]:
dataset.isnull().any()

ID                       False
LIMIT_BAL                False
SEX                      False
EDUCATION_DONE_OR_NOT    False
MARRIAGE                 False
AGE                      False
PAY_0                    False
PAY_2                    False
PAY_3                    False
PAY_4                    False
PAY_5                    False
PAY_6                    False
BILL_AMT1                False
BILL_AMT2                False
BILL_AMT3                False
BILL_AMT4                False
BILL_AMT5                False
BILL_AMT6                False
PAY_AMT1                 False
PAY_AMT2                 False
PAY_AMT3                 False
PAY_AMT4                 False
PAY_AMT5                 False
PAY_AMT6                 False
default                  False
dtype: bool

In [63]:
dataset.head(10)

ID  LIMIT_BAL SEX  EDUCATION_DONE_OR_NOT  MARRIAGE  AGE  PAY_0  PAY_2  \
0   1      20000   F                      1         0   24      2      2   
1   2     120000   F                      1         1   26     -1      2   
2   3      90000   F                      1         0   34      0      0   
3   4      50000   F                      1         1   37      0      0   
4   5      50000   M                      1         1   57     -1      0   
5   6      50000   M                      1         1   37      0      0   
6   7     500000   M                      0         1   29      0      0   
7   8     100000   F                      1         1   23      0     -1   
8   9     140000   F                      1         1   28      0      0   
9  10      20000   M                      0         1   35     -2     -2   

   PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -1     -1  ...          0          0          0         0       689   
1      0      0  ...       3272       3455       3261         0      1000   
2      0      0  ...      14331      14948      15549      1518      1500   
3      0      0  ...      28314      28959      29547      2000      2019   
4     -1      0  ...      20940      19146      19131      2000     36681   
5      0      0  ...      19394      19619      20024      2500      1815   
6      0      0  ...     542653     483003     473944     55000     40000   
7     -1      0  ...        221       -159        567       380       601   
8      2      0  ...      12211      11793       3719      3329         0   
9     -2     -2  ...          0      13007      13912         0         0   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default   
0         0         0         0         0         Y  
1      1000      1000         0      2000         Y  
2      1000      1000      1000      5000         N  
3      1200      1100      1069      1000         N  
4     10000      9000       689       679         N  
5       657      1000      1000       800         N  
6     38000     20239     13750     13770         N  
7         0       581      1687      1542         N  
8       432      1000      1000      1000         N  
9         0     13007      1122         0         N  

[10 rows x 25 columns]

In [64]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
dataset["LIMIT_BAL"] = le.fit_transform(dataset["LIMIT_BAL"])


In [65]:
dataset["SEX"] = le.fit_transform(dataset["SEX"])

In [66]:
x = dataset.iloc[:, 3:24].values  # input
y = dataset.iloc[:, 24].values  # output


In [67]:
dataset

ID  LIMIT_BAL  SEX  EDUCATION_DONE_OR_NOT  MARRIAGE  AGE  PAY_0  \
0          1          2    0                      1         0   24      2   
1          2         12    0                      1         1   26     -1   
2          3          9    0                      1         0   34      0   
3          4          5    0                      1         1   37      0   
4          5          5    1                      1         1   57     -1   
...      ...        ...  ...                    ...       ...  ...    ...   
29995  29996         22    1                      1         1   39      0   
29996  29997         15    1                      1         1   43     -1   
29997  29998          3    1                      1         1   37      4   
29998  29999          8    1                      1         0   41      1   
29999  30000          5    1                      1         1   46      0   

       PAY_2  PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
0          2     -1     -1  ...          0          0          0         0   
1          2      0      0  ...       3272       3455       3261         0   
2          0      0      0  ...      14331      14948      15549      1518   
3          0      0      0  ...      28314      28959      29547      2000   
4          0     -1      0  ...      20940      19146      19131      2000   
...      ...    ...    ...  ...        ...        ...        ...       ...   
29995      0      0      0  ...      88004      31237      15980      8500   
29996     -1     -1     -1  ...       8979       5190          0      1837   
29997      3      2     -1  ...      20878      20582      19357         0   
29998     -1      0      0  ...      52774      11855      48944     85900   
29999      0      0      0  ...      36535      32428      15313      2078   

       PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default   
0           689         0         0         0         0         Y  
1          1000      1000      1000         0      2000         Y  
2          1500      1000      1000      1000      5000         N  
3          2019      1200      1100      1069      1000         N  
4         36681     10000      9000       689       679         N  
...         ...       ...       ...       ...       ...       ...  
29995     20000      5003      3047      5000      1000         N  
29996      3526      8998       129         0         0         N  
29997         0     22000      4200      2000      3100         Y  
29998      3409      1178      1926     52964      1804         Y  
29999      1800      1430      1000      1000      1000         Y  

[30000 rows x 25 columns]

In [68]:
x

array([[    1,     0,    24, ...,     0,     0,     0],
       [    1,     1,    26, ...,  1000,     0,  2000],
       [    1,     0,    34, ...,  1000,  1000,  5000],
       ...,
       [    1,     1,    37, ...,  4200,  2000,  3100],
       [    1,     0,    41, ...,  1926, 52964,  1804],
       [    1,     1,    46, ...,  1000,  1000,  1000]])

In [69]:
y

array(['Y', 'Y', 'N', ..., 'Y', 'Y', 'Y'], dtype=object)

In [70]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
import numpy as np

# Assuming x contains your input data

# Identify categorical columns that need encoding (assuming column index 2 contains strings)
categorical_cols = [2]

# Apply Label Encoding to convert categorical columns to numeric
label_encoders = {}
for col in categorical_cols:
    label_encoders[col] = LabelEncoder()
    x[:, col] = label_encoders[col].fit_transform(x[:, col])

# Debug print to see the result of Label Encoding
print("After Label Encoding:")
print(x)

# Apply OneHotEncoder to the transformed categorical columns
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), categorical_cols)], remainder='passthrough')
x = np.array(ct.fit_transform(x))



After Label Encoding:
[[    1     0     3 ...     0     0     0]
 [    1     1     5 ...  1000     0  2000]
 [    1     0    13 ...  1000  1000  5000]
 ...
 [    1     1    16 ...  4200  2000  3100]
 [    1     0    20 ...  1926 52964  1804]
 [    1     1    25 ...  1000  1000  1000]]


In [72]:
z

NameError: name 'z' is not defined

In [73]:
x

array(<30000x76 sparse matrix of type '<class 'numpy.float64'>'
	with 479044 stored elements in Compressed Sparse Row format>,
      dtype=object)

In [74]:
y

array(['Y', 'Y', 'N', ..., 'Y', 'Y', 'Y'], dtype=object)

In [75]:
y.shape

(30000,)

In [76]:
print("Shape of y:", x.shape)



Shape of y: ()


In [77]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Assuming you have loaded your dataset into a DataFrame called 'dataset'

# Extract features (input) and labels (output)
x = dataset.iloc[:, :-1].values  # Features (all columns except the last one)
y = dataset.iloc[:, -1].values   # Labels (last column)

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [78]:
x_test.shape

(6000, 24)

In [79]:
y_test.shape

(6000,)

In [80]:
from sklearn.model_selection import train_test_split
x1 = [1,2,3,4,5,6,7,8,9,10]
y1 = [1,0,1,0,1,0,1,0,1,0]
for i in range(5):
    x_train1,x_test1,y_train1,y_test1 = train_test_split(x1,y1,test_size = 0.2,random_state = 2)
    print(x_train1,"with Random State")

[6, 1, 8, 3, 4, 7, 10, 9] with Random State
[6, 1, 8, 3, 4, 7, 10, 9] with Random State
[6, 1, 8, 3, 4, 7, 10, 9] with Random State
[6, 1, 8, 3, 4, 7, 10, 9] with Random State
[6, 1, 8, 3, 4, 7, 10, 9] with Random State


In [81]:
for i in range(5):
    x_train1,x_test1,y_train1,y_test1 = train_test_split(x1,y1,test_size = 0.2)
    print(x_train1,"without Random State")

[5, 7, 9, 6, 2, 3, 1, 4] without Random State
[4, 10, 6, 3, 1, 9, 7, 8] without Random State
[10, 3, 7, 1, 6, 5, 4, 9] without Random State
[9, 10, 4, 1, 3, 2, 7, 5] without Random State
[8, 7, 6, 5, 9, 3, 4, 1] without Random State


In [82]:
from sklearn.preprocessing import LabelEncoder

# Assuming x contains your input data

# Identify categorical columns that need encoding (assuming column index 2 contains strings)
categorical_cols = [2]

# Apply Label Encoding to convert categorical columns to numeric
label_encoders = {}
for col in categorical_cols:
    label_encoders[col] = LabelEncoder()
    x[:, col] = label_encoders[col].fit_transform(x[:, col])

# Check if Label Encoding is applied correctly
print("After Label Encoding:")
print(x)


After Label Encoding:
[[    1     2     0 ...     0     0     0]
 [    2    12     0 ...  1000     0  2000]
 [    3     9     0 ...  1000  1000  5000]
 ...
 [29998     3     1 ...  4200  2000  3100]
 [29999     8     1 ...  1926 52964  1804]
 [30000     5     1 ...  1000  1000  1000]]


In [83]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Encode the target variable 'y'
y_encoded = label_encoder.fit_transform(y)

# Now 'y_encoded' contains the numerical labels for the target variable


In [84]:
import numpy as np

# Check if there are any non-numeric values in the features
for i, col in enumerate(x.T):
    if not np.issubdtype(col.dtype, np.number):
        print(f"Column {i} contains non-numeric data.")




In [85]:
# Check the data types of all columns
for i, col in enumerate(x.T):
    if not np.issubdtype(col.dtype, np.number):
        print(f"Column {i} contains non-numeric data.")


In [86]:
from sklearn.ensemble import RandomForestClassifier

# Create a RandomForestClassifier instance with specified parameters
forest_reg = RandomForestClassifier(n_estimators=10, criterion="entropy", random_state=42)

# Train the classifier using the training data
forest_reg.fit(x_train, y_train)

# Once trained, you can use the classifier for predictions or evaluation


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=42)

In [87]:
x_train[0]

array([21754,     8,     0,     1,     1,    24,     0,     0,     0,
           0,     0,     0, 75125, 77353, 78321, 73731, 39643, 39457,
        3503,  5001,  2092,  1218,  1445,   878])

In [88]:
y_train

array(['N', 'N', 'N', ..., 'N', 'Y', 'Y'], dtype=object)

In [111]:
from ibm_watson_machine_learning import APIClient

wml_credentials = {
    "url": "https://us-south.ml.cloud.ibm.com",
    "apikey": "buehbprgidd6ZXCAcQdfcRWbwZk8FTENj4_jFXJEELSJ"
}

client = APIClient(wml_credentials)


In [99]:
def guid_from_space_name(client, space_name):
    spaces = client.spaces.get_details()
    for item in spaces['resources']:
        if item['entity']['name'] == space_name:
            return item['metadata']['id']


In [100]:
space_uid = guid_from_space_name(client, 'models')
print("Space UID:", space_uid)


Space UID: 2385b1c2-5161-4da6-9719-7faef9e8db0e


In [101]:
client.set.default_space(space_uid)

'SUCCESS'

In [102]:
software_spec_uid = client.software_specifications.get_uid_by_name("default_py3.7")
software_spec_uid

'e4429883-c883-42b6-87a8-f419d64088cd'

In [103]:
client.software_specifications.list()

----------------------------  ------------------------------------  ----  ------------  --------------------------
NAME                          ID                                    TYPE  STATE         REPLACEMENT
default_py3.6                 0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base  retired       runtime-22.2-py3.10
autoai-ts_rt23.1-py3.10       01ce9391-1a79-5a33-94fb-2e134337f314  base  supported
kernel-spark3.2-scala2.12     020d69ce-7ac1-5e68-ac1a-31189867356a  base  retired
pytorch-onnx_1.3-py3.7-edt    069ea134-3346-5748-b513-49120e15d288  base  retired
tensorflow_rt23.1-py3.10      079a91e0-245f-5269-8926-3c20b28f37dc  base  supported
scikit-learn_0.20-py3.6       09c5a1d0-9c1e-4473-a344-eb7b665ff687  base  retired       runtime-22.2-py3.10
spark-mllib_3.0-scala_2.12    09f4cff0-90a7-5899-b9ed-1ef348aebdee  base  retired
pytorch-onnx_rt22.1-py3.9     0b848dd4-e681-5599-be41-b5f6fccc6471  base  retired       pytorch-onnx_rt22.2-py3.10
ai-function_0.1-py3.6         0cdb0f1e-5

NAME                                    ID  TYPE  \
0                  default_py3.6  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base   
1        autoai-ts_rt23.1-py3.10  01ce9391-1a79-5a33-94fb-2e134337f314  base   
2      kernel-spark3.2-scala2.12  020d69ce-7ac1-5e68-ac1a-31189867356a  base   
3     pytorch-onnx_1.3-py3.7-edt  069ea134-3346-5748-b513-49120e15d288  base   
4       tensorflow_rt23.1-py3.10  079a91e0-245f-5269-8926-3c20b28f37dc  base   
5        scikit-learn_0.20-py3.6  09c5a1d0-9c1e-4473-a344-eb7b665ff687  base   
6     spark-mllib_3.0-scala_2.12  09f4cff0-90a7-5899-b9ed-1ef348aebdee  base   
7      pytorch-onnx_rt22.1-py3.9  0b848dd4-e681-5599-be41-b5f6fccc6471  base   
8          ai-function_0.1-py3.6  0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base   
9                     shiny-r3.6  0e6e79df-875e-4f24-8ae9-62dcc2148306  base   
10  tensorflow_2.4-py3.7-horovod  1092590a-307d-563d-9b62-4eb7d64b3f22  base   
11             pytorch_1.1-py3.6  10ac12d6-6b30-4ccd-8392-3e922c096a92  base   
12     tensorflow_1.15-py3.6-ddl  111e41b3-de2d-5422-a4d6-bf776828c4b7  base   
13       autoai-kb_rt22.2-py3.10  125b6d9a-5b1f-5e8d-972a-b251688ccf40  base   
14        watsonx-textgen-fm-1.0  129aec82-7e65-5c78-b812-4c0a74b916f5  base   
15            runtime-22.1-py3.9  12b83a17-24d8-5082-900f-0ab31fbfd3cb  base   
16           masking-flows-spark  13666829-5570-53a7-927b-52d42a101d93  base   
17        kernel-spark3.3-py3.10  147e6777-ccd1-5886-8571-5356abc20839  base   
18       scikit-learn_0.22-py3.6  154010fa-5b3b-4ac1-82af-4d5ee5abbc85  base   
19    pytorch-onnx_rt23.1-py3.10  195067e6-4c5e-5fab-8bd0-e7623a88b4d3  base   
20                  default_r3.6  1b70aec3-ab34-4b87-8aa0-a4a3c8296a36  base   
21        pytorch-onnx_1.3-py3.6  1bc6029a-cc97-56da-b8e0-39c3880dbbe7  base   
22          kernel-spark3.3-r3.6  1c9e5454-f216-59dd-a20e-474a5cdf5988  base   
23          tensorflow_2.1-py3.6  1eb25b84-d6ed-5dde-b6a5-3fbdf1665666  base   
24               spark-mllib_3.2  20047f72-0a98-58c7-9ff5-a77b012eb8f5  base   
25  tensorflow_2.4-py3.8-horovod  217c16f6-178f-56bf-824a-b19f20564c49  base   
26       runtime-22.1-py3.9-cuda  26215f05-08c3-5a41-a1b0-da66306ce658  base   
27                      do_py3.8  295addb5-9ef9-547e-9bf4-92ae3563e720  base   
28           autoai-ts_3.8-py3.8  2aa0c932-798f-5ae9-abd6-15e0c2402fb5  base   
29         tensorflow_1.15-py3.6  2b73a275-7cbf-420b-a912-eae7f436e0bc  base   
30         kernel-spark3.3-py3.9  2b7961e2-e3b1-5a8c-a491-482c8368839a  base   
31             pytorch_1.2-py3.6  2c8ef57d-2687-4b7d-acce-01f94976dac1  base   
32               spark-mllib_2.3  2e51f700-bca0-4b0d-88dc-5c6791338875  base   
33    pytorch-onnx_1.1-py3.6-edt  32983cea-3f32-4400-8965-dde874a8d67e  base   
34           runtime-23.1-py3.10  336b29df-e0e1-5e7d-b6a5-f6ab722625b2  base   
35          spark-mllib_3.0-py37  36507ebe-8770-55ba-ab2a-eafe787600e9  base   
36               spark-mllib_2.4  390d21f8-e58b-4fac-9c55-d7ceda621326  base   
37       autoai-ts_rt22.2-py3.10  396b2e83-0953-5b86-9a55-7ce1628a406f  base   
38            xgboost_0.82-py3.6  39e31acd-5f30-41dc-ae44-60233c80306e  base   
39    pytorch-onnx_1.2-py3.6-edt  40589d0e-7019-4e28-8daa-fb03b6f4fe12  base   
40    pytorch-onnx_rt22.2-py3.10  40e73f55-783a-5535-b3fa-0c8b94291431  base   
41               default_r36py38  41c247d3-45f8-5a71-b065-8580229facf0  base   
42        autoai-ts_rt22.1-py3.9  4269d26e-07ba-5d40-8f66-2d495b0c71f7  base   
43                autoai-obm_3.0  42b92e18-d9ab-567f-988a-4240ba1ed5f7  base   
44                  pmml-3.0_4.3  493bcb95-16f1-5bc5-bee8-81b8af80e9c7  base   
45         spark-mllib_2.4-r_3.6  49403dff-92e9-4c87-a3d7-a42d0021c095  base   
46            xgboost_0.90-py3.6  4ff8d6c2-1343-4c18-85e1-689c965304d3  base   
47        pytorch-onnx_1.1-py3.6  50f95b2a-bc16-43bb-bc94-b0bed208c60b  base   
48           autoai-ts_3.9-py3.8  52c57136-80fa-572e-8728-a5e7cbb42cde  base   
49    spark-mllib_2.4-scala_

In [ ]:
model_id

In [ ]:
x_train[0]

In [ ]:
y_train[0]

In [ ]:
# Assuming forest.reg is your trained random forest regressor
forest_reg.predict([[21754, 8, 0, 1, 1, 24, 0, 0, 0, 0, 0, 0, 75125, 77353, 78321, 73731, 39643, 39457, 3503, 5001, 2092, 1218, 1445, 878]])





In [106]:
import os

os.environ['IBM_CLOUD_API_KEY'] = 'buehbprgidd6ZXCAcQdfcRWbwZk8FTENj4_jFXJEELSJ'